// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Non-secret, durable metadata for a hosted workspace patch.
 */
export type AgentPatchArtifactMetadata = { artifactId: string, agentId: string, baseSnapshotId: string, checksum: string, changedFiles: number, sizeBytes: number, };
