// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentPatchArtifactMetadata } from "./AgentPatchArtifactMetadata";

/**
 * Delivered only to subscribers of the owner eligible to apply this patch.
 */
export type AgentPatchAvailableNotification = { threadId: string, artifact: AgentPatchArtifactMetadata, };
