// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PathUri } from "../PathUri";

export type AgentPatchApplyResponse = { "type": "applied" } | { "type": "conflict", paths: Array<PathUri>, } | { "type": "rejected", reason: string, };
